---
title: "About this Shiny Application"
author: "Ashish Mungi"
date: "21 August 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## About this application - "mtcars Data Explorer"

This is a Shiny web application - "mtcars Data Explorer". 

This web application is created for the course project: Coursera - Developing Data Products

It consists of two files: ui.R and server.R

The application can be used for an analysis of the `mtcars` dataset in R.

The `mtcars` dataset has 32 observations of 11 variables, comprising fuel consumption (MPG), and 11 other design aspects for 32 cars.


1. **mpg**	Miles/(US) gallon
2. **cyl**	Number of cylinders
3. **disp**	Displacement (cu.in.)
4. **hp**	Gross horsepower
5. **drat**	Rear axle ratio
6. **wt**	Weight (1000 lbs)
7. **qsec**	1/4 mile time
8. **vs**	V/S
9. **am**	Transmission (0 = automatic, 1 = manual)
10. **gear**	Number of forward gears
11. **carb**	Number of carburetors


## Tab: Raw Data

The **Raw Data** tab lists the raw data from the `mtcars` dataset in a table format.

* Each variable is listed in a column, which can be sorted.
* There are 32 rows, each representing the observation for 1 car each. Car Model is listed in the first column.

## Tab: Summary

The Summary tab displays the summary of the `mtcars` dataset.

## Tab: Regression

The Regression tab can be used to explore the regression output of Miles Per Gallon (mpg) as the output, with a combination of different predictors (am, wt, qsec, cyl).

* The user can select or deselect the checkboxes to choose their combination of predictors.
* If none of the predictors are chosen, the linear model output for mpg with all predictors (i.e. **mpg ~ .**) is displayed.

The reactive output changes based on the user input (in selecting or deselecting the checkboxes).